//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v10.3.0-rc+0dc577b
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq.Expressions;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.PublishedCache;
using Umbraco.Cms.Infrastructure.ModelsBuilder;
using Umbraco.Cms.Core;
using Umbraco.Extensions;

namespace Our.Umbraco.ContentList.Web.Models
{
	// Mixin Content Type with alias "listableContent"
	/// <summary>Listable Content</summary>
	public partial interface IListableContent : IPublishedContent
	{
		/// <summary>List heading</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.3.0-rc+0dc577b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string ListHeading { get; }

		/// <summary>List image</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.3.0-rc+0dc577b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		global::Umbraco.Cms.Core.Models.MediaWithCrops ListImage { get; }

		/// <summary>List summary</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.3.0-rc+0dc577b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		global::Umbraco.Cms.Core.Strings.IHtmlEncodedString ListSummary { get; }

		/// <summary>Read more text</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.3.0-rc+0dc577b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string ReadMoreText { get; }
	}

	/// <summary>Listable Content</summary>
	[PublishedModel("listableContent")]
	public partial class ListableContent : PublishedContentModel, IListableContent
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.3.0-rc+0dc577b")]
		public new const string ModelTypeAlias = "listableContent";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.3.0-rc+0dc577b")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.3.0-rc+0dc577b")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public new static IPublishedContentType GetModelContentType(IPublishedSnapshotAccessor publishedSnapshotAccessor)
			=> PublishedModelUtility.GetModelContentType(publishedSnapshotAccessor, ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.3.0-rc+0dc577b")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(IPublishedSnapshotAccessor publishedSnapshotAccessor, Expression<Func<ListableContent, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(publishedSnapshotAccessor), selector);
#pragma warning restore 0109

		private IPublishedValueFallback _publishedValueFallback;

		// ctor
		public ListableContent(IPublishedContent content, IPublishedValueFallback publishedValueFallback)
			: base(content, publishedValueFallback)
		{
			_publishedValueFallback = publishedValueFallback;
		}

		// properties

		///<summary>
		/// List heading
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.3.0-rc+0dc577b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("listHeading")]
		public virtual string ListHeading => GetListHeading(this, _publishedValueFallback);

		/// <summary>Static getter for List heading</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.3.0-rc+0dc577b")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetListHeading(IListableContent that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "listHeading");

		///<summary>
		/// List image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.3.0-rc+0dc577b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("listImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops ListImage => GetListImage(this, _publishedValueFallback);

		/// <summary>Static getter for List image</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.3.0-rc+0dc577b")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static global::Umbraco.Cms.Core.Models.MediaWithCrops GetListImage(IListableContent that, IPublishedValueFallback publishedValueFallback) => that.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(publishedValueFallback, "listImage");

		///<summary>
		/// List summary
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.3.0-rc+0dc577b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("listSummary")]
		public virtual global::Umbraco.Cms.Core.Strings.IHtmlEncodedString ListSummary => GetListSummary(this, _publishedValueFallback);

		/// <summary>Static getter for List summary</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.3.0-rc+0dc577b")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static global::Umbraco.Cms.Core.Strings.IHtmlEncodedString GetListSummary(IListableContent that, IPublishedValueFallback publishedValueFallback) => that.Value<global::Umbraco.Cms.Core.Strings.IHtmlEncodedString>(publishedValueFallback, "listSummary");

		///<summary>
		/// Read more text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.3.0-rc+0dc577b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("readMoreText")]
		public virtual string ReadMoreText => GetReadMoreText(this, _publishedValueFallback);

		/// <summary>Static getter for Read more text</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.3.0-rc+0dc577b")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetReadMoreText(IListableContent that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "readMoreText");
	}
}
